const employees = [
  {
    id: "11D001",
    name: "MAGHESH",
    email: "magesh@Dotcod.in",
    joinDate: "4/15/23",
    designation: "Software Engineer",
    status: "Confirmed",
    createdDate: "1/1/23",
    releavedDate: null,
    salaryHikeByDate: "5/1/23",
    mobileNumber: "9876543210",
    dateOfBirth: "1995-06-15",
    gender: "Male",
    maritalStatus: "Single",
    isPhysicallyChallenged: false,
    bloodGroup: "O+",
    personalEmail: "magesh.personal@mail.com",
  },
  {
    id: "11D002",
    name: "Tesla",
    email: "Rshahull@Dotcod.in",
    joinDate: "1/2/23",
    designation: "Product Manager",
    status: "Probation",
    createdDate: "12/1/22",
    releavedDate: null,
    salaryHikeByDate: "4/1/23",
    mobileNumber: "9988776655",
    dateOfBirth: "1998-12-01",
    gender: "Female",
    maritalStatus: "Married",
    isPhysicallyChallenged: false,
    bloodGroup: "A+",
    personalEmail: "tesla.personal@mail.com",
  },
  {
    id: "11D003",
    name: "GM",
    email: "gm@Dotcod.in",
    joinDate: "9/4/23",
    designation: "Software Engineer",
    status: "Confirmed",
    createdDate: "8/1/23",
    releavedDate: null,
    salaryHikeByDate: "12/1/23",
    mobileNumber: "9876543211",
    dateOfBirth: "1992-04-25",
    gender: "Male",
    maritalStatus: "Single",
    isPhysicallyChallenged: true,
    bloodGroup: "B+",
    personalEmail: "gm.personal@mail.com",
  },
  {
    id: "11D004",
    name: "AARP",
    email: "aarp@Dotcod.in",
    joinDate: "6/3/22",
    designation: "UX/UI Designer",
    status: "Probation",
    createdDate: "5/1/22",
    releavedDate: "12/1/23",
    salaryHikeByDate: "10/1/22",
    mobileNumber: "9123456789",
    dateOfBirth: "1994-08-14",
    gender: "Male",
    maritalStatus: "Divorced",
    isPhysicallyChallenged: false,
    bloodGroup: "O-",
    personalEmail: "aarp.personal@mail.com",
  },
  {
    id: "11D005",
    name: "Disney",
    email: "disney@Dotcod.in",
    joinDate: "12/2/22",
    designation: "HR Manager",
    status: "Confirmed",
    createdDate: "11/1/22",
    releavedDate: null,
    salaryHikeByDate: "4/1/23",
    mobileNumber: "9345678901",
    dateOfBirth: "1997-01-10",
    gender: "Female",
    maritalStatus: "Married",
    isPhysicallyChallenged: false,
    bloodGroup: "AB+",
    personalEmail: "disney.personal@mail.com",
  },
  {
    id: "11D006",
    name: "Chevy",
    email: "chevy@Dotcod.in",
    joinDate: "4/19/23",
    designation: "Software Engineer",
    status: "Probation",
    createdDate: "3/1/23",
    releavedDate: null,
    salaryHikeByDate: "8/1/23",
    mobileNumber: "9871234567",
    dateOfBirth: "1996-09-30",
    gender: "Female",
    maritalStatus: "Single",
    isPhysicallyChallenged: false,
    bloodGroup: "A-",
    personalEmail: "chevy.personal@mail.com",
  },
];

const leaveRequests = [
  {
    name: "MAGHESH",
    email: "magesh@Dotcod.in",
    requestDate: "6/3/22",
    leaveType: "Casual Leave",
    reason: "Not Well",
    noDays: 1,
    status: "Pending",
  },
  {
    name: "Tesla",
    email: "Rsahull@Dotcod.in",
    requestDate: "12/2/22 - 16/02/22",
    leaveType: "Sick Leave",
    reason: "Not Well",
    noDays: 4,
    status: "Approved",
  },
  {
    name: "GM",
    email: "gm@Dotcod.in",
    requestDate: "4/19/23",
    leaveType: "Casual Leave",
    reason: "Sick Leave",
    noDays: 1,
    status: "Approved",
  },
  {
    name: "AARP",
    email: "aarp@Dotcod.in",
    requestDate: "1/2/23",
    leaveType: "Sick Leave",
    reason: "Marriage Function",
    noDays: 1,
    status: "Approved",
  },
  {
    name: "Disney",
    email: "Disney@Dotcod.in",
    requestDate: "9/4/23",
    leaveType: "Sick Leave",
    reason: "Marriage Function",
    noDays: 1,
    status: "Approved",
  },
  {
    name: "Prime Therapeutics",
    email: "PrimeTherapeutics@Dotcod.in",
    requestDate: "12/2/22 - 16/02/22",
    leaveType: "Sick Leave",
    reason: "Marriage Function",
    noDays: 3,
    status: "Approved",
  },
];

const attendances = [
  {
    name: "MAGHESH",
    email: "magesh@Dotcod.in",
    joinDate: "4/15/23",
    designation: "Software Engineer",
    status: "Confirmed",
    createdDate: "1/1/23",
    releavedDate: null,
    salaryHikeByDate: "5/1/23",
  },
  {
    name: "Tesla",
    email: "Rshahull@Dotcod.in",
    joinDate: "1/2/23",
    designation: "Product Manager",
    status: "Probation",
    createdDate: "12/1/22",
    releavedDate: null,
    salaryHikeByDate: "4/1/23",
  },
  {
    name: "GM",
    email: "gm@Dotcod.in",
    joinDate: "9/4/23",
    designation: "Software Engineer",
    status: "Confirmed",
    createdDate: "8/1/23",
    releavedDate: null,
    salaryHikeByDate: "12/1/23",
  },
  {
    name: "AARP",
    email: "aarp@Dotcod.in",
    joinDate: "6/3/22",
    designation: "UX/UI Designer",
    status: "Probation",
    createdDate: "5/1/22",
    releavedDate: "12/1/23",
    salaryHikeByDate: "10/1/22",
  },
  {
    name: "Disney",
    email: "disney@Dotcod.in",
    joinDate: "12/2/22",
    designation: "Marketing Lead",
    status: "Confirmed",
    createdDate: "11/1/22",
    releavedDate: null,
    salaryHikeByDate: "4/1/23",
  },
  {
    name: "Chevy",
    email: "chevy@Dotcod.in",
    joinDate: "4/19/23",
    designation: "HR Manager",
    status: "Probation",
    createdDate: "3/1/23",
    releavedDate: null,
    salaryHikeByDate: "8/1/23",
  },
];
